name: Bug Report
description: Report a problem with ionis-validate
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
      placeholder: "When I ran `ionis-validate predict ...` I got an error..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Run `ionis-validate predict --tx-grid XX00 ...`
        2. See error
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste any error messages or stack traces
      render: shell
    validations:
      required: false

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: "Paste output from `ionis-validate info`"
      render: shell
    validations:
      required: true
